### ISSUE TITLE
Dokumentasi di http://judgels.readthedocs.org masih belum di update

### ISSUE THREAD

**Issue by matematikaadit** [judgels/judgels#31]
Perintah installasi di http://judgels.readthedocs.org/en/latest/setup.html masih mengarah ke repositori yang lama di https://github.com/ia-toki

```
cd <your-Judgels-base-directory>
git clone https://github.com/ia-toki/judgels
```

Request untuk diupdate. Atau barangkali pakai [autoupdate-nya readthedocs](https://docs.readthedocs.org/en/latest/webhooks.html)

**Comment by fushar** [comment]
Terima kasih atas laporannya @matematikaadit, namun saat ini tim sedang mengerjakan prioritas lain. Apakah kamu sedang mencoba install Judgels? Barangkali mau bantu update dokumentasi via pull request? :)

**Comment by matematikaadit** [comment]
Iya, lagi nyobain install.

Kalau yang di reponya sendiri sih udah up-to-date, https://github.com/judgels/judgels/blob/master/docs/setup.rst. Cuman yang di situs readthedocs.org tadi yang out-of-date. Petunjuk di README.md bilang kalau instruksi instalasinya ada di http://judgels.readthedocs.org/, jadi baru sadar belakangan kalau isinya beda.
