### ISSUE TITLE
bug di uriel

### ISSUE THREAD

**Issue by fatanugraha** [judgels/judgels#33]
jam kompetisi di uriel menggunakan jam komputer lokal, bukan berdasarkan jam server.
![capture](https://cloud.githubusercontent.com/assets/4775076/10241516/c9534f26-6913-11e5-8deb-d2ed4ab31dd9.PNG)
Jam lokal saya unsychronized (jam 3:04) sedangkan server 2:40, tapi tulisannya sudah mulai kontesnya.

**Comment by dronjax** [comment]
resolved in judgels/play-commons@94365c19d7c98364d5e6b5fc5f64ed8ba6e994ce
