### ISSUE TITLE
~/.bashrc for Mac OS

### ISSUE THREAD

**Issue by alijaya** [judgels/judgels#48]
According to documentation, if we write this in ~/.bashrc

```
cd $JUDGELS_HOME
judgels/scripts/download-activator.sh
```

It will be loaded only if we write `/bin/bash` in terminal.

I sugges to write this thing in `~/.bash_profile` instead.

**Comment by dronjax** [comment]
http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

Read part of the Mac OS.

I think we should adapt to production environment (Linux Ubuntu).

Maybe you can do pull request and can add Mac OS part.
